module.exports = {
  GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
  GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY,

  DIALOGFLOW_SESSION_ID: process.env.DIALOGFLOW_SESSION_ID,
  DIALOGFLOW_SESSION_LANGUAGE_CODE: process.env.DIALOGFLOW_SESSION_LANGUAGE_CODE
};
